### ISSUE TITLE
filter by category works wrong

### ISSUE THREAD

**Issue by acrontum** [andywarren/aw-yearly-category-archives#2]
I see there is an wrong attribute in the WP_Query. You should use there 'cat' and not 'category'. Works better. 
Found in aw_yearlyCategory_archives_plugin.php at line 86 and 230.

Thanks

**Comment by andywarren** [comment]
Line 86: ` $myposts = get_posts(array('posts_per_page' => -1, 'post_type' => $postTypes, 'category' => $cat, 'post_status' => 'publish', 'orderby' => 'post_date'));` 

This is using the `get_posts()` function. The correct parameter for this when querying by category is `category`, not `cat`.  Please see the Codex for further explanation: http://codex.wordpress.org/Template_Tags/get_posts#Usage

I'll update line 230 when I get some time; however if you'd care to explain why `cat` works better than `category` that would be great. It appears to me that either or wok just find.

**Comment by acrontum** [comment]
category at line 230 don't work at my installation. So I changed it and it works. I don't why other have the same problem. 
You had two issues at the tracker, maybe they had the same error.

**Comment by andywarren** [comment]
I really don't have an explanation as to why it didn't work for you, but I have updated the plugin both here and in the plugin repo. Please go ahead and install the latest version. Thanks for pointing it out to me.

**Comment by acrontum** [comment]
Thanks for update. 
Works great :)
